platform :ios, '10.0'

use_frameworks!

target 'AXPhotoViewerExample' do

  pod 'Reveal-SDK'

  # Loading spinner
  pod 'DRPLoadingSpinner'

  # Image downloading / caching
  pod 'PINRemoteImage', '~> 3.0.0-beta.9'

  # AXPhotoViewer
  pod 'AXPhotoViewer/PINRemoteImage', :path => '../../AXPhotoViewer.podspec'

end
